### ISSUE TITLE
List Sort on Catalog

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-latest-earthquakes#112]
While implementing the SettingsView I noticed that the only list setting that didn't work was the listSort setting.

**Comment by emartinez-usgs** [comment]
IMO - Sorting should be done in the catalog and the listView itself just renders the catalog in whichever order it is currently in. This would happen because catalog.sort() will trigger a "reset" event, which causes a listSort.render to occur.

**Comment by jmfee-usgs** [comment]
👍

**Comment by emartinez-usgs** [comment]
- The `onSort` method should not require a `method` argument, but should instead read the current `sort` property off the model.
- Test has unused imports
- Test has missing semicolons
- Make tests for `onSort` method more atomic.
  - Check that `onSort` is called when the model `sort` property changes (sinon.spy)
  - Verify the `sort` method (in Collection) is called with the correct sort method (sinon.spy)

**Comment by emartinez-usgs** [comment]
The existing sort order is not preserved when the feed changes. For example:

- Select 7 Day 4.5+ feed
- Sort by largest magnitude first
- Switch to 7 Day 2.5+ feed
- Observe earthquakes are not listed largest magnitude first.

**Comment by emartinez-usgs** [comment]
The list now double-renders. The collection.reset call triggers "reset" event and, in-turn, a render. Then onSort calls sort which also triggers a reset and, in-turn, a render.
