### ISSUE TITLE
Add controls to map.

### ISSUE THREAD

**Issue by hasimpson-usgs** [usgs/earthquake-latest-earthquakes#125]
Need to add the ZoomToControl,  LegendView, and mouse position, and other controls to the map,  when available.

**Comment by emartinez-usgs** [comment]
Either update the attribution control to be styled with hazdev-leaflet styles, or potentially remove it from map. We document layer attribution on the general help/documentation/about page for the application.

**Comment by emartinez-usgs** [comment]
- Include default styles from hazdev-leaflet for other controls.
- Remove unnecessary styles from _MapView.scss.
- Simplify selectors in _MapView.scss

Consider overhauling layout for controls in map. Put all controls in same container. Give container `display: flex` and `justify-content: space-between`. Simply show/hide legend based on screen sizes.

Always add mouse position control on desktop, never on mobile. Don't worry about screen size to conditionally hide that control.
