### ISSUE TITLE
EventSummaryView

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-latest-earthquakes#141]
Create the EventSummaryView which uses the EventSummaryFormat to summarize the event.

The EventSummaryView should be added to the footer by in LatestEarthquakes, and should be bound to select (and deselect) on the Catalog.

**Comment by jmfee-usgs** [comment]
fyi, the catalog doesn't trigger select/deselect; the view should monitor the model "event" property which will either contain the selected event, or be null if no event is selected.

**Comment by emartinez-usgs** [comment]
- Test page can not find summary/EventSummaryView
- Nothing seems to display.

**Comment by emartinez-usgs** [comment]
- Use MMI colors from `_mmi-variables.scss`
- Remove unused `clearfix` class from impact bubbles container
- Event bindings by reference should use a private function that calls a public function.
- The show/hide logic seems circular as-is, instead maybe ...
  - When the close button is clicked, set the model event property to null
    - This can directly trigger the render
  - In the render function, pull the currently selected event off the model
  - If not null, update the event summary and show it.
  - If null, clear event summary and hide it.

**Comment by ehunter-usgs** [comment]
To address your last comment I just combined the logic from onEventSelect() into render() I think this makes it more clear?
