### ISSUE TITLE
Persist map position in url

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-latest-earthquakes#151]

**Comment by jmfee-usgs** [comment]
To reproduce:
- Load page
- Move map
- Refresh page => view switches back to default

**Comment by emartinez-usgs** [comment]
To clarify: Map position is properly saved in the URL already, however, when the page is loaded, the MapView does not honor the saved position.

**Comment by jmfee-usgs** [comment]
when page is loaded, or when bookmark is loaded (hash changes externally)
