### ISSUE TITLE
loading with multiple modes selected

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-latest-earthquakes#162]
When on mobile, only one mode can be selected,  however when a bookmark is loaded in mobile with multiple modes selected they all appear selected in the interface.

**Comment by emartinez-usgs** [comment]
Try doing this with CSS instead.

- When updating the "selected" class on the icon itself, also add a view-mode class for the selected view mode to the ModesView itself.
- Create CSS rules to target when multiple views are enable on small screens, similar to...
```css
.list-view.map-view .map.selected,
.list-view.settings-view .settings.selected,
.map-view.settings-view .settings.selected { !selected }
```
