### ISSUE TITLE
Large Feed Warnings

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-latest-earthquakes#179]
Use a warning dialog to warn the user before rendering a large feed. The definition of "large" varies based on browser. Look at implementation from previous map/list for a starting point.

**Comment by ehunter-usgs** [comment]
Comments are on the PR

**Comment by ehunter-usgs** [comment]
I think that all of the view/dialog related stuff should be in its own class. FeedWarningView?
