### ISSUE TITLE
Leaflet Cursor

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-latest-earthquakes#182]
Change the default cursor over the map to be the `default` (arrow) cursor. Do this in hazdev-leaflet to affect all our maps.

**Comment by llastowka-usgs** [comment]
+1

**Comment by ehunter-usgs** [comment]
I wouldn't have agreed with this, but Lynda +1'd the issue

**Comment by llastowka-usgs** [comment]
Some things are just too important to ignore. :arrow_right: > :hand:
