### ISSUE TITLE
change settings in listview footer

### ISSUE THREAD

**Issue by hasimpson-usgs** [usgs/earthquake-latest-earthquakes#199]
Remove quotes from "Settings"
Make it a link that will opens up the settings view.

**Comment by emartinez-usgs** [comment]
Move the `updateModel` method from the `ModesView` instance method to a static helper. This can either be on the `ModesView` itself, or into a separate utility class.

The `renderFooter` method is called repeatedly during the rendering process. It should not repeatedly create event listeners. This can be corrected be rendering less often, or by using event delegation.
