### ISSUE TITLE
MapView Test

### ISSUE THREAD

**Issue by jdbrown-USGS** [usgs/earthquake-latest-earthquakes#223]

**Comment by ehunter-usgs** [comment]
Good start. Can we add tests for the rest of the methods:
 - deselectEventonMoveEnd
 - isFilteredEnabled
 - onBasemapChange
 - render
 - renderBasemapChange
 - renderOverlayChange
 - renderViewModesChange

**Comment by jdbrown-USGS** [comment]
- Added test for deselectEventonMoveEnd and IsFilteredEnabled
- Refactored MapView to make onBasemapChange etc testable - Tests still needed.
- MapView will require more refactor to make the other methods testable.
