### ISSUE TITLE
Rotating screen causes text zoom

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-latest-earthquakes#226]
When switching between portait and landscape on your phone the text in the list items will become enlarged.

**Comment by ehunter-usgs** [comment]
I thought this was going to be the solution:
`<meta name="viewport" content="width=device-width, initial-scale=1">`
However, we already have that meta tag...

**Comment by jmfee-usgs** [comment]
This seems related:
http://stackoverflow.com/questions/2710764/preserve-html-font-size-when-iphone-orientation-changes-from-portrait-to-landsca?answertab=active#tab-top

**Comment by ehunter-usgs** [comment]
should we just add this to the template?
