### ISSUE TITLE
revertToDefaultFeed not setting focus.

### ISSUE THREAD

**Issue by hasimpson-usgs** [usgs/earthquake-latest-earthquakes#233]
When revertToDefaultFeed is called,  the focus is still on the last feed selected.

**Comment by ehunter-usgs** [comment]
This can be replicated by loading a feed that exceeds the warning size of 2,000 events.  If the user selects "Show Realtime Data Instead" the focus remains on the previously selected feed input.

**Comment by ehunter-usgs** [comment]
![screen shot 2016-06-14 at 1 44 55 pm](https://cloud.githubusercontent.com/assets/1932750/16057218/4619401a-3236-11e6-9245-5313cab46540.png)
