### ISSUE TITLE
LargeFeedWarning.

### ISSUE THREAD

**Issue by hasimpson-usgs** [usgs/earthquake-latest-earthquakes#237]
Back button while largefeedwarning dialog is up,  doesn't behave directly.

**Comment by ehunter-usgs** [comment]
data fails to load, if you follow these steps:
- load the application
- select a large feed > 2,000 events
- click "show realtime data instead"
- you get an error

**Comment by ehunter-usgs** [comment]
@emartinez-usgs could you review this since jonathan  is out and hal and I both worked on it?
