### ISSUE TITLE
Use hex codes instead of ligatures for Material Icons

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-latest-earthquakes#255]
The ligatures seem to be breaking in IE event though they should work for IE9+, these should be switched anywhere that they are used in this application:
- navigation
- about section
- others?

For example:
```
<!-- For modern browsers. -->
<i class="material-icons">settings</i>
<!-- For IE9 or below. -->
<i class="material-icons">&#xE8B8;</i>
```

**Comment by jmfee-usgs** [comment]
I think this is only when viewing on localhost, or similar.  Try using your IP address or hostname.

**Comment by ehunter-usgs** [comment]
@jmfee-usgs I was viewing the production pages on earthquake.usgs.gov

**Comment by emartinez-usgs** [comment]
Older browsers will have difficulties with ligatures.  Hex codes seem more universal.
