### ISSUE TITLE
Map refocuses on selected event when settings are changed

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-latest-earthquakes#258]
If you scroll away from a selected event and change (let's say) the map baselayer, the map re-centers on the selected event. This is frustrating behavior, but not critical to change. You could always deselect the event to stop it from happening. 

To recreate:
 - Open the map and settings
 - Deselect “Only List Earthquakes Shown on Map” filter
 - Select an event
 - Pan away from the select event until it is out of view
 - Select a non-feed option in the settings (a feed could deselect the event and avoid this bug)
 - The map will pan and re-center the selected event that is no longer in view

I think that the map should only center on the selected event when an event is selected, not when any settings option is updated.

**Comment by jmfee-usgs** [comment]
deselecting the event when it is no longer visible is one way to address this
