### ISSUE TITLE
Zoom to control broken in Edge browser

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-latest-earthquakes#259]
When you click on the "Zoom To" control nothing happens

**Comment by ehunter-usgs** [comment]
If we make this work I would be in favor of not forcing the (+/-) controls to always be visible. It ends of feeling crowded on mobile.

**Comment by ehunter-usgs** [comment]
Fixed by https://github.com/usgs/hazdev-leaflet/pull/20

**Comment by jmfee-usgs** [comment]
comments on https://github.com/usgs/hazdev-leaflet/pull/20
