### ISSUE TITLE
Scrolling issue on list (iOS devices)

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-latest-earthquakes#261]
With the updated layout to use absolute positioning instead of flexbox, we reintroduced a scrolling issue on the list. However, it doesn't seem to be happening in the settings panel like it used to. 

To recreate (on iPhone):
 - scroll all the way to the bottom of the list (make sure you get the elastic bounce indicating the end of the list)
 - after the bounce stops, continue scrolling down.
 - you should be able scroll past the bottom by about 75%

**Comment by ehunter-usgs** [comment]
![scrolling-issue](https://cloud.githubusercontent.com/assets/1932750/16530590/1017c966-3f86-11e6-92ea-a8be7e3aad6c.png)

**Comment by ehunter-usgs** [comment]
This is due to the fact that the EventSummaryView is being positioned with a `bottom: -500px;` to hide it from view. 

Could we also add a style to have the EventSummaryView `display: none;` but apply this style/class with a `window.setTimeout` that runs after the animation has finished?

**Comment by jmfee-usgs** [comment]
As long as that timeout is cleared if another earthquake is selected first.  Alternatively, could you use an animation with keyframes, so it is hidden during the last 1% of the animation?
