### ISSUE TITLE
Move "Zoom To" Control to top right

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-latest-earthquakes#264]
This was suggested by a user and I agree. Even more so now that we are always showing the ( + | - ) control (even on mobile).

**Comment by emartinez-usgs** [comment]
More generally I would suggest we make the "Zoom To" aesthetically "fit in" better on the map. Maybe the control itself needs some design love. Positioning is another option.

**Comment by ehunter-usgs** [comment]
This was completed in another ticket.
