### ISSUE TITLE
malfunctions of the new release

### ISSUE THREAD

**Issue by lorenzozyby** [usgs/earthquake-latest-earthquakes#272]
Sir,
       I already reported several malfunctions of this release but I saw no care to fix them.
For instance: what sense does it make to show all continents up to a dozen of times?

The most annoying one is the dragging: 

Magnifying the map of clicking on a point allows dragging but ONLY FOR ONE TIME!
Any attempt after the first drag are ignored and force to go back to Zooming On <location>
to start all over again.  This malfunction was not present in the previous release.

System Windows 7 SP1, Firefox 48.0

Hoping for a fix I thank you.

Regards,
lorenzo

**Comment by jmfee-usgs** [comment]
Fixes for these issues are underway.

Until those are released, the panning issues are related to problems handling existing bookmarks.  Try visiting the application directly ( http://earthquake.usgs.gov/earthquakes/map ), changing desired settings, and creating a _new_ bookmark.

**Comment by ehunter-usgs** [comment]
This appears to be fixed, reopen if it is not.
