### ISSUE TITLE
Legend needs to be updated to reflect the new gray color EQ symbols

### ISSUE THREAD

**Issue by lisa-usgs** [usgs/earthquake-latest-earthquakes#281]
Looks like there are now gray EQ symbols on the map for EQ Search results when the events are older than 30 days, but the legend at the bottom of the map was not updated to reflect this new symbol color.
![screen shot 2016-09-13 at 10 13 26 am](https://cloud.githubusercontent.com/assets/4162494/18481855/100dede8-799b-11e6-9645-6ba1524b9626.png)

**Comment by jmfee-usgs** [comment]
I believe the grays are a depth scale.  This will need to be handled similarly to other overlays (like Hazard, ShakeMap, DYFI, etc)

**Comment by lisa-usgs** [comment]
The grays are associated with depth on the interactive map, but on the map/list for the search results, the colors are associated with earthquake age.  These grays appear to be for earthquakes older than 30 days.
