### ISSUE TITLE
Add scenario branding

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-latest-earthquakes#285]
There is some creative freedom in how this is done, but it should very clearly indicate that people are viewing scenarios. I would consider using the same tactic from the catalog search page where an alert is clearly listed at the top of the page.

http://earthquake.usgs.gov/scenarios/search/

![screen shot 2016-12-07 at 3 10 49 pm](https://cloud.githubusercontent.com/assets/1932750/20988771/662a26c4-bc8f-11e6-8584-437b6cae3e4e.png)

**Comment by jmfee-usgs** [comment]
You may want to match what is done on the interactive map:
http://earthquake.usgs.gov/scenarios/eventpage/aklegacy1938kodiak_se#map
