### ISSUE TITLE
Update Feeds

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-latest-earthquakes#288]
When the scenario mode is enabled, the earthquake feeds should be replaced with scenario catalogs. 

The available scenario catalogs should be read out of the database, but the list includes:
- Aklegacy
- Bssc2014
- Hvlegacy
- Mt2016
- Nclegacy
- Nnlegacy
- Sclegacy
- US - National Earthquake Information Center, PDE
- Uulegacy

Order the catalogs in alphabetical order.
The BSSC catalog should be selected by default.

**Comment by jmfee-usgs** [comment]
Here is a link to the JSON feed:
http://earthquake.usgs.gov/scenarios/catalog/index.json.php
