### ISSUE TITLE
Update default settings

### ISSUE THREAD

**Issue by ehunter-usgs** [usgs/earthquake-latest-earthquakes#292]
The following settings options should be selected by default:

Earthquakes
 - BSSC 

List Format
 - ShakeMap

List Sort Order
 - Largest Magnitude First

Filter
 - Only List Earthquakes Shown on Map

Map Layers
 - Grayscale

Overlays
 - plates
 - faults

If a setting option is not listed, it is because it should have been removed from settings.

**Comment by jdbrown-USGS** [comment]
This was done in a previous ticket.
