### ISSUE TITLE
Update ESRI basemaps

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-latest-earthquakes#41]
Currently cached tiles for grayscale layer, possibly others, are out of date.

Option 1 (preferred):
- update to load tiles directly from ESRI.

Option 2:
- update cached tiles in hazdev-basemap.

**Comment by jmfee-usgs** [comment]
Additionally, update documentation of layers so it is clearer which map provider and data are shown.

**Comment by jmfee-usgs** [comment]
Use the basemaps from hazdev-leaflet.

**Comment by jdbrown-USGS** [comment]
https://github.com/usgs/hazdev-leaflet/pull/15

**Comment by emartinez-usgs** [comment]
Intent for hazdev-leaflet project was to implement a "Provider" layer base class. This class would create a generic tile layer based on a static constant provider key. This provider layer could potentially be extended once for each type of tile layer basemap (i.e. "Grayscale", "Terrain", "Satellite", etc...). For example:
```javascript
var Grayscale = require('leaflet/layer/Grayscale');
// ...
var layer;

layer = Grayscale(Grayscale.ESRI);
```

**Comment by jdbrown-USGS** [comment]
Same pull request

**Comment by emartinez-usgs** [comment]
Update to use new classes.

**Comment by emartinez-usgs** [comment]
Be sure to configure the terrain layer to use the NatGeo terrain layer.
