### ISSUE TITLE
Broken links in doc_aboutdata.php

### ISSUE THREAD

**Issue by lisa-usgs** [usgs/earthquake-latest-earthquakes#42]
Hazard Faults Database
NEIC
Maryland Geological Survey
Virginia Tech
Ohio Seismic Network
USGS Menlo
USGS Pasadena
http://earthquake.usgs.gov/regional/neic/
http://earthquake.usgs.gov/regional/sca/

**Comment by jmfee-usgs** [comment]
This has already moved to http://earthquake.usgs.gov/data/comcat/
