### ISSUE TITLE
display search inputs

### ISSUE THREAD

**Issue by llastowka-usgs** [usgs/earthquake-latest-earthquakes#48]
somehow display search inputs on list. bottom?

**Comment by ehunter-usgs** [comment]
I think we want to add these to the accordion in the header. I created a mockup for discussion. 

![screen shot 2016-06-13 at 9 17 06 am](https://cloud.githubusercontent.com/assets/1932750/16012665/bcb65ebe-3147-11e6-8b42-b28c5f7a702b.png)

**Comment by emartinez-usgs** [comment]
I would suggest you indicate somewhere in the interface that those are search parameters. It may also be nice to provide a link to edit the search as well...
