### ISSUE TITLE
Documentation Pages

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-latest-earthquakes#52]
Migrate documentation pages out of project.

- doc_aboutdata.php
- doc_help.php
- doc_whicheqs.php

The first page has already been migrated to the catalog docs in the website as part of usgs/earthquake-website#52. The other pages need a home. Exactly where this home may be is still TBD.

Update links to documentation.

**Comment by emartinez-usgs** [comment]
Note: Browser support documentation should be updated as part of this. The statement that the current and previous versions is not quite accurate given Microsoft has stopped support for IE 10 and and introduced Edge.

**Comment by jmfee-usgs** [comment]
I believe these are now part of the pages in /data/comcat/
