### ISSUE TITLE
Implement ZoomTo leaflet control

### ISSUE THREAD

**Issue by lisa-usgs** [usgs/earthquake-latest-earthquakes#54]
There are so many earthquakes in parts of the Central U.S. that this would be used by many people who live in those states.  Please check with Rob Williams on map extent to display for this zoom.

**Comment by jmfee-usgs** [comment]
Reimplement zoom to control.
Only need drop down, use built in leaflet controls for +/-.
Add Central US and Oklahoma to zoom to options, remove My Location (will use geolocate control).

**Comment by llastowka-usgs** [comment]
I don't know if anyone checked with Rob, I suggest something like this to get started... 
http://earthquake.usgs.gov/earthquakes/map/#%7B%22feed%22%3A%221day_m25%22%2C%22search%22%3Anull%2C%22listFormat%22%3A%22default%22%2C%22sort%22%3A%22newest%22%2C%22basemap%22%3A%22grayscale%22%2C%22autoUpdate%22%3Atrue%2C%22restrictListToMap%22%3Atrue%2C%22timeZone%22%3A%22utc%22%2C%22mapposition%22%3A%5B%5B32.657875736955305%2C-104.27124023437499%5D%2C%5B40.26276066437183%2C-88.13232421875%5D%5D%2C%22overlays%22%3A%7B%22plates%22%3Atrue%7D%2C%22viewModes%22%3A%7B%22list%22%3Atrue%2C%22map%22%3Atrue%2C%22settings%22%3Afalse%2C%22help%22%3Afalse%7D%7D

**Comment by hasimpson-usgs** [comment]
https://github.com/usgs/hazdev-location-view/pull/78

**Comment by emartinez-usgs** [comment]
See comments on related pull request.

**Comment by emartinez-usgs** [comment]
See recent comments on related pull request.
