### ISSUE TITLE
ShakeMapListFormat

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-latest-earthquakes#58]
The "shakemap" list format.  Do not extend View.

Methods:
```
/**
 * Format an item for the list.
 *
 * @param eq {Object}
 *     a feature object (not model) from the summary feed.
 * @return {DOMElement}
 *     dom element with formatted information.
 */
_this.format = function (eq) {
    // TODO
}
```

Create example.
Create test.

**Comment by jmfee-usgs** [comment]
list/ShakeMapListFormat

**Comment by emartinez-usgs** [comment]
- Remove .tmp and .sass-cache from .gitignore (and from your file system). These are artifacts of the old build system and should no longer exist.

- Use the static example JSON available in the etc folder for your example page. Feel free to replace that with more interesting JSON if you want to see more events with ShakeMaps, but we should snapshot this for consistency. The current 7day feed is quite active...
- Don't use complicated `reduce` loop in example page. Examples should be clear to the ready, hence, a good example. See current PagerListFormatExample.js for a simplified implementation.

- Do not import _mmi-variables in multiple places. If possible, it is best to put all imports into the main index.scss file.
- Stylistic comment here, but I would prefer some left/right padding around the MMI value.

- Options are already extended outside the `_intiailize` method. No need to re-extend them inside the method.

- Do not declare and define variables on the same line.
- Improve test for `getCalloutMarkup`. Simple enough to check full string returned is correct.
- Add test for `getClasses`
- Add test for `getHeaderMarkup`
