### ISSUE TITLE
DyfiListFormat

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-latest-earthquakes#59]
The "dyfi" list format.  Do not extend View.

Methods:
```
/**
 * Format an item for the list.
 *
 * @param eq {Object}
 *     a feature object (not model) from the summary feed.
 * @return {DOMElement}
 *     dom element with formatted information.
 */
_this.format = function (eq) {
    // TODO
}
```

Create example.
Create test.

**Comment by jmfee-usgs** [comment]
list/DyfiListFormat

**Comment by ehunter-usgs** [comment]
https://github.com/ehunter-usgs/earthquake-latest-earthquakes/tree/usgs/earthquake-latest-earthquakes%2359

I still need to create tests and examine for extraneous styles/code.
