### ISSUE TITLE
ListView

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-latest-earthquakes#62]
list/ListView

- Receives application model.
- Displays events in collection, which is model property "catalog".
- Uses one of the list formatters to format items, which is model property "listFormat"
- Use a delegated event listener to trigger collection select events when a user clicks on an event.
- Use a data-id attribute on list items to tell which earthquake was clicked.

Don't worry about header/footer as part of this ticket (but create a header and footer element).

**Comment by jmfee-usgs** [comment]
create example
create test

**Comment by emartinez-usgs** [comment]
Updated usage shows a ListView instantiated as follows:
```
ListView({
      el: HTMLElement,
      catalog: Catalog,
      config: Config,
      model: Model
    });
```
