### ISSUE TITLE
ListView header

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-latest-earthquakes#63]
Format information for list view header.

TBD.

**Comment by hasimpson-usgs** [comment]
Title should remain as it is.
Second line should be 
"X of Z earthquakes in map area."
or
"Y earthquakes"
Depending on whether "Only List Earthquakes Shown on Map"  property restrictListToMap  is enabled, and there is a map extents.

Second line is the Accordion toggle, expands to show update times, and download button should open modal with a download view.  
Might include search parameters.

**Comment by ehunter-usgs** [comment]
please rebase.
