### ISSUE TITLE
List View footer

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-latest-earthquakes#64]
Format information for ListView footer.

TBD

**Comment by emartinez-usgs** [comment]
This should not be a separate class, but rather should implement the `renderFooter` method on the `list/ListView` class. Remove example pages and remove from browserify. Move tests into ListViewTest.js

- Apostrophe should be marked up as `&apos;`
- Should not be marked up as a description list. Use a simple header (h3 or something) and then a simple unordered list of links/info.

**Comment by jdbrown-USGS** [comment]
- Removed ListViewFooter and added markup to ListView.
- fixed Apostrophe.
- changed from a description list to an unordered list

**Comment by emartinez-usgs** [comment]
- Link to unknown event form should be: "/earthquakes/eventpage/unknown#tellus"
- Move declaration and definition of view into the "it" test rather than using a "before".

**Comment by emartinez-usgs** [comment]
Provide better CSS for this content. Check with @ehunter-usgs  or @shaefner-usgs

**Comment by ehunter-usgs** [comment]
please rebase.
