### ISSUE TITLE
Help View

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-latest-earthquakes#69]
Content for the help page

**Comment by lisa-usgs** [comment]
Text, URLs and order for Links:

- Help - Latest Earthquakes - http://earthquake.usgs.gov/data/comcat/latest-eqs.php
- ANSS Comprehensive Earthquake Catalog (ComCat) Documentation - http://earthquake.usgs.gov/data/comcat/
- Earthquake Hazards Program
- Contact Us - http://earthquake.usgs.gov/contactus/

**Comment by emartinez-usgs** [comment]
- Use the help_outline icon for the help icon.
- Update markup/styles for the "In Partnership" section to look more like the following:

![in-partnership](https://cloud.githubusercontent.com/assets/1726751/14716770/b14ee9e4-07ab-11e6-9f38-bfba3bcab68e.png)

- View implementation is a little wonky. Perhaps provide the element into which the view should be rendered during construction and auto-render the view. In this way, the usage might be like:

```javascript
var HelpView = require('help/HelpView');


HelpView({
  el: document.querySelector('.help-view-container')
});
```
- Make sure source code wraps at or before 80 characters. The data uri strings are exempt from this.
- Style rules within each selector should be in alphabetical order.
- Style imports in index.scss should be in alphabetical order
- Remove `alt` attribute from images and add a relevant `aria-described-by` attribute instead which references the full text corresponding to the partner logo. (https://www.w3.org/WAI/GL/wiki/Using_aria-describedby_to_provide_descriptions_of_images)
