### ISSUE TITLE
MapView

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-latest-earthquakes#70]
Display the earthquake layer, manage leaflet controls including zoom, scale, position, layers

**Comment by hasimpson-usgs** [comment]
Needs to watch basemap, overlays, map position and event properties on model.

**Comment by hasimpson-usgs** [comment]
Will not have a layers control at this time.

**Comment by emartinez-usgs** [comment]
- Should initialize map with `fitBounds` rather than `setView`
- Need to watch `overlays` property on model to update overlays
- Should `moveEnd` be watched by the map itself or the `_earthquakes` layer internally?

... more to do on this in general ...

**Comment by hasimpson-usgs** [comment]
Can't get fitBounds to work rather then setView.   Evidently there's a known bug where fitBounds called immediately after setView locks up.   And the initialize method in leaflet calls setView.
