### ISSUE TITLE
list format control

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-latest-earthquakes#78]
for settings view

**Comment by jmfee-usgs** [comment]
set application model property "listFormat"

**Comment by emartinez-usgs** [comment]
- "Settings" section should come before "Summary" section in `_navigation.inc.php`
- Use the lobotomized owl trick to put borders between items.
- CheckboxOptionsView.js internally creates something called "RadioOptionsView" which is just confusing.
- Make better use of class inheritance.
  - Use either the radio or checkbox version as a parent to the other class, it should implement the `deselectAll` and `setSelected` methods.
  - Do not override the `render` method itself, instead...
    - Set the default `containerNodeName` option on this class to be an `ol`.
    - Override the `createCollectionItemContent`.
- Do not call render during initialization.
  - This may require the examples be updated.
